service: aws-serverless-express-starter
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"

functions:
  api:
    handler: express/app.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
